# -*- coding: utf-8 -*-
"""Revised pre-proposal content. Each item is (kind, text).

kinds: TITLE, H1, H2, P (first-line indent), PL (flush left), FIG (figure slot),
       CAP (caption), TBLROW, REF
Inline markup: **bold**, *italic*
"""

C = []
A = C.append

A(("TITLE", "Illness or Lithium? Separating Medication Effects From Disease Effects in the Bipolar Blood Transcriptome"))

# ------------------------------------------------------------------ 1
A(("H1", "1. Background and Motivation"))

A(("P", "Bipolar disorder is a mood disorder characterized by episodes of mania and depression. It is strongly heritable: twin and family studies attribute roughly 60–85% of the variance in liability to the disorder to genetic differences between individuals (Barnett & Smoller, 2009). That figure is a population-level statement about how much of the variation in risk across people tracks genetic variation; it is not a claim that genes supply 60–85% of any one person’s risk. Despite this heritability, the pathophysiology of bipolar disorder remains poorly understood, and whole-blood gene expression has been proposed as an accessible window onto disease mechanism and as a possible source of a diagnostic biomarker."))

A(("P", "With that intention, Krebs et al. (2020) performed differential expression analysis on whole-blood RNA-sequencing from 480 subjects: unaffected controls, bipolar subjects taking lithium, and bipolar subjects not taking lithium. The difficulty is that medication is almost perfectly nested inside diagnosis in this cohort. No control takes lithium, and of the 226 bipolar I subjects, 152 do and only 74 do not. Any gene that separates cases from controls may therefore be tracking lithium exposure rather than the illness itself."))

A(("P", "There is a concrete mechanism by which that could happen. Lithium raises circulating neutrophil counts, an effect documented in the hematology literature for decades (Barr & Galbraith, 1983) and attributed to GSK-3 phosphorylation and HIF-1 stabilisation (Kast, 2008). Critically, **Krebs et al. (2020) themselves reported elevated neutrophil proportions in the lithium users of this very dataset**, so the mechanism is not hypothetical here — it is already an observed feature of the data we propose to analyse. Whole blood is a mixture, and its bulk expression profile is the abundance-weighted average of the profiles of its constituent cell types. If lithium shifts that mixture toward neutrophils, bulk expression changes arithmetically, without any individual cell altering its transcriptional behaviour (Wang et al., 2016). A gene list produced under these conditions describes a change in blood composition rather than a change in cell biology, even though the two are indistinguishable in a bulk assay."))

A(("P", "The follow-up paper, Boltz et al. (2024), deconvolved bulk-blood RNA-seq from this and related cohorts and compared lithium-associated expression with and without adjustment for cell-type proportions. **They continued to detect lithium-associated genes after adjusting for composition.** An earlier draft of this pre-proposal stated that lithium’s effect appears only in bulk and not in single cell types; that was a misreading of their result and we correct it here. The corrected finding is more useful to us than the misreading was, because it establishes that composition does not account for the whole of lithium’s effect and therefore makes the scientific question quantitative rather than binary. The question is not *whether* lithium acts through cell mix, but *what proportion* of its effect does so, with what uncertainty, and whether that proportion is large enough that a routine blood count would carry the same information as a transcriptome."))

A(("P", "A second and separate problem concerns the case-versus-control comparison. Krebs et al. included lithium use as a covariate when testing for differential expression between cases and controls. Because lithium use is almost perfectly nested inside case status, adjusting for it removes a substantial share of the very contrast being estimated: the model is asked to explain case–control differences while holding fixed a variable that is itself close to a marker of being a case. This is over-adjustment, and its consequence is that the reported diagnosis effect is not an estimate of the case–control difference in the source population. It is an estimate of that difference in a hypothetical population where medication does not vary with diagnosis. Our re-analysis does not adjust for lithium. It instead restricts cases to the 74 bipolar I subjects who do not take lithium and compares them directly with controls, so that medication is excluded by design rather than adjusted away. Because the estimand differs, the resulting gene list may differ, and that difference is the result of interest rather than a discrepancy to be explained away."))

A(("H2", "1.1 What this project adds beyond Boltz et al. (2024)"))

A(("P", "Boltz et al. analysed 1,730 samples from the same research group and have already compared lithium effects with and without composition adjustment. It is a fair objection that re-checking mediation in a subset of their data is not, by itself, a project. Our contribution is not a new dataset or a claim of discovery; it is that three questions Boltz et al. left informal are turned into properly specified statistical tests, and a fourth is asked for the first time."))

A(("PL", "**(i) The prediction claim is currently untested.** The observation that cell-composition features classify lithium use about as well as full expression appears in Boltz et al. as essentially a single sentence supported by one 70/30 split, with no cross-validation, no null model and no equivalence margin. A single 30% test split of 226 bipolar I subjects yields roughly 68 test samples, about 22 of them non-users; a single 10% split, as our own earlier draft proposed, yields about 23 samples and 7 non-users. Neither can support a claim that two classifiers perform equivalently, because an equivalence claim requires a confidence interval narrow enough to exclude a pre-declared difference, and at those sample sizes the interval on an AUC difference spans most of the achievable range. We replace the single split with repeated nested cross-validation, a permutation null, and an equivalence margin declared in advance. This converts an informal observation into a claim that is capable of failing."))

A(("PL", "**(ii) Covariate adjustment is not a decomposition.** Adjusting for cell proportions and observing that lithium-associated genes survive establishes that the association is not wholly explained by composition. It does not partition lithium’s effect into a part transmitted through composition and a part that is not, and it attaches no number to either. Mediation analysis performs exactly that partition, and it is a different estimand resting on different assumptions. We estimate the proportion mediated, test the exposure–mediator interaction that the estimator assumes away, bound unmeasured confounding with E-values, and correct for the fact that the mediator is estimated rather than measured."))

A(("PL", "**(iii) Nobody has addressed the circularity.** In every analysis of this kind, including ours, the cell fractions are estimated from the same expression matrix that serves as the mediation outcome. For the genes that drive the deconvolution this is close to tautological. Neither Krebs et al. nor Boltz et al. quantify how much of the apparent mediation is an artifact of that dependency. Section 4.6 sets out three specific procedures for doing so and one honest statement of what remains."))

A(("PL", "**(iv) Composition adjustment cannot answer a question about coordination.** Adjusting for cell proportions asks whether the mean expression of a gene shifts. It cannot ask whether the *pattern of covariation between genes* differs, because a covariance structure is not a quantity that a linear covariate adjustment acts on. If lithium changes how genes are co-regulated, rather than only which cells are present, that is a behavioural effect and it is invisible to the analyses performed to date. The network arm asks that question, and then asks whether any answer survives removing composition."))

A(("P", "The motivation for this rigour is applied rather than aesthetic. A blood biomarker for bipolar disorder would be most valuable in patients who have never been treated, since those are the patients whose diagnosis is still in question. A biomarker trained on an almost entirely medicated cohort, and validated without separating medication from illness, is precisely the biomarker that would fail in that population. Establishing how much of the reported signal is medication is therefore a prerequisite for the clinical use the original work proposes, not a footnote to it."))

# ------------------------------------------------------------------ 2
A(("H1", "2. Hypotheses"))

A(("P", "We state four hypotheses separately, each with a numerical threshold fixed before any result is examined. The first three carry the project’s conclusions; the fourth is declared exploratory for reasons of power given in Section 6.3."))

A(("PL", "**H1 (primary, prediction).** Five isometric log-ratio (ILR) coordinates derived from blood cell fractions classify lithium use as accurately as the full filtered gene expression matrix, where “as accurately as” means that the two-sided 95% confidence interval on the difference in cross-validated AUC lies entirely within an equivalence margin of **ΔAUC = 0.05**. The margin is declared now; a margin chosen after seeing results is not a test."))

A(("PL", "**H2 (secondary, mediation).** The proportion of lithium’s total effect on gene expression that is transmitted through cell composition, aggregated across tested genes, **exceeds 0.5** after correction for mediator measurement error. “Significant proportion” was undefined in our earlier draft; 0.5 is the threshold we commit to."))

A(("PL", "**H3 (exploratory, networks).** Gene co-expression module structure differs across controls, bipolar subjects off lithium, and bipolar subjects on lithium, where “differs” means **at least one module with a Zsummary preservation statistic below 2**, pooled across subsampling draws and surviving Benjamini–Hochberg correction. With 12,353 genes some module will always appear to differ by eye, so a threshold is required for the statement to have content."))

A(("PL", "**H4 (exploratory, declared underpowered).** The cell-mediated component of age’s effect on gene expression is larger in lithium users than in non-users (Salarda et al., 2021). This is a moderated-mediation hypothesis, structurally distinct from H1–H3. Section 6.3 shows that we are not powered to test it at these group sizes. We will report it as an estimate with an interval and no significance claim, and it will not contribute to the project’s conclusions."))

A(("H2", "2.1 Why equal prediction would not by itself demonstrate mediation"))

A(("P", "Our earlier draft chained H1 and H2 into a single sentence, implying that equivalent prediction would establish mediation. It would not, and the two must be stated separately. The ILR coordinates are computed from the same expression matrix that serves as the mediation outcome, so they can classify lithium use accurately while carrying none of lithium’s causal effect: prediction requires only that the coordinates be *associated* with lithium, whereas mediation requires that they lie on the causal path from lithium to expression. Association is symmetric and cheap; mediation is directional and expensive."))

A(("P", "A third comparator separates the two, and we add it to the prediction contest for exactly this purpose: **gene expression residualised on the ILR coordinates**, that is, the component of expression orthogonal to cell composition. If composition-free expression still classifies lithium above the permutation null, then a route from lithium to expression exists that does not pass through cell mix, and the mediated proportion must be strictly less than one no matter how well the ILR coordinates predict. If instead residualised expression falls to the null while the ILR coordinates retain their accuracy, then composition is not merely sufficient for detection but exhausts the detectable signal. The three-way comparison — genes, ILR coordinates, residualised genes — is what makes the prediction arm informative about mediation rather than merely suggestive of it, and the residualised arm is the specific result that discriminates between the two readings."))

# ------------------------------------------------------------------ 3
A(("H1", "3. Dataset"))

A(("P", "The dataset is GEO accession GSE124326, comprising whole-blood RNA-seq from 480 samples. Both files have been downloaded and parsed. The count matrix is **57,820 genes × 480 samples** of raw integer HTSeq union-mode counts, with Ensembl identifiers carrying version suffixes and no duplicates after those suffixes are stripped. That gene total is exactly the GENCODE v19 count, which pins the annotation to GENCODE v19 / Ensembl 74 / GRCh37. Forty-seven ENSGR rows are pseudoautosomal-region Y duplicates carrying 1,518 counts in total and are dropped, leaving a working matrix of **57,773 × 480**. The series matrix supplies 35 characteristics fields per sample; these lines are ragged across samples, so each field is parsed by its own content rather than by row position. Column names in the count matrix are sample titles rather than GSM accessions, and after removing a “.counts” suffix they match the metadata title field for all 480 samples. We join on that key rather than on column order."))

A(("P", "Applying the deposited quality flag leaves **444 samples: 226 bipolar I, 13 bipolar II, 205 controls.** No bipolar II subject takes lithium, so every lithium contrast is bipolar I only: **74 non-users against 152 users**, a split unchanged by quality control. Krebs et al. report 227 bipolar I, 13 bipolar II and 204 controls post-QC; the deposit disagrees with the publication by one subject in two places. We report the deposit and note the discrepancy rather than adjusting our counts to match the paper."))

A(("H2", "3.1 The quality flag is not random with respect to diagnosis"))

A(("P", "The 36 excluded samples are **35 of 240 controls, 1 of 14 bipolar II and 0 of 226 bipolar I** (Fisher exact **p = 3.04 × 10⁻¹⁰**). Exclusion is therefore strongly associated with diagnosis, which matters because every case–control comparison in this dataset consequently runs on a filtered control group, while the lithium contrast does not. Decomposing the exclusions: 32 samples are missing demographic fields, predominantly tobacco use, and 4 have complete data — identifiers 099252A, 108773A, 118140B and 118141A, which correspond to the four sample mix-ups Krebs et al. describe. The mix-ups are identity errors and cannot be recovered by imputation. We flag the filtered control group wherever a case–control analysis appears, including the illness retest of Section 4.8."))

A(("H2", "3.2 Missingness and imputation"))

A(("P", "Our earlier draft stated that we might use imputation to fill in missing fields, without identifying which fields those were. Having checked, **all analysis covariates are complete for all 444 retained samples**: age, sex, tobacco use, assessment group, RIN, sequencing plate and the three deposited sequencing-metric principal components have zero missingness post-QC. There is consequently nothing to impute in the primary analysis, and that sentence is withdrawn."))

A(("P", "Imputation remains relevant for one specific and optional purpose. The 32 controls excluded for missing demographics are recoverable in principle, and because exclusion is diagnosis-associated, recovering them would test whether case–control conclusions depend on the non-random filter. We therefore pre-specify a **sensitivity analysis only**, not a change to the primary sample: multiple imputation by chained equations (Rubin, 1987) applied to the missing covariates of those 32 controls, five imputations, results pooled by Rubin’s rules. Three constraints are fixed now. **Exposure and outcome variables are never imputed** — lithium use and diagnosis are observed or the subject is excluded. Imputation models are **fitted inside training folds only** and applied to held-out data, never fitted on the full cohort. And the four sample mix-ups remain excluded from every analysis, since imputation cannot repair a subject-identity error."))

A(("H2", "3.3 Variables"))

A(("P", "Exposure is lithium use, within bipolar I subjects only; diagnosis is the exposure for the illness retest. Covariates are age, sex, tobacco use, assessment group, RIN, sequencing plate and three deposited sequencing-metric principal components. The mediator is blood cell composition, entering as ILR coordinates built from the retained cell-type fractions. Two covariate facts bear directly on confounding. Age differs with lithium within bipolar I (non-users median 54.8 years, users 48.9, p = 0.0034) and must therefore be adjusted. Tobacco use, by contrast, is **balanced with lithium within bipolar I** (35.1% against 31.6%, p = 0.70); it is imbalanced across the whole cohort (controls 19.0%, bipolar I 32.7%), and an earlier note of ours describing it as a confounder of the lithium contrast was computed across the full cohort and is wrong for this contrast. Sequencing plate is likewise balanced with lithium (χ² p = 0.97). Assessment group is **constant within bipolar I** — all 226 are in group A — and must be dropped from any bipolar-I-only design matrix, which would otherwise be singular."))

A(("H2", "3.4 Variables that do not exist in this dataset"))

A(("P", "Three variables that would materially improve the analysis are absent from the deposit, and we confirmed their absence by enumerating all 35 characteristics fields rather than assuming it. **There is no BMI or body-composition field**, so body fat cannot be adjusted for and must instead be bounded, which is why the E-value approach of Section 4.5 is used in place of direct adjustment. **There is no record of other medications.** Most bipolar I subjects not taking lithium are likely to be taking some other psychotropic agent, and we cannot identify which; the unmedicated-case comparison of Section 4.8 therefore controls for lithium but not for antipsychotics, anticonvulsants or antidepressants, and its gene list must be read as “cases not on lithium” rather than “unmedicated cases”. **There is no lithium dose or serum level**, so exposure is necessarily binary and no dose–response relationship can be examined; if a true dose–response exists, our binary contrast underestimates lithium’s effect. All three are reported as limitations rather than worked around silently."))

A(("H2", "3.5 Library size and RNA quality require our own screen"))

A(("P", "The deposited quality flag does not screen sequencing depth or RNA integrity, so we apply our own thresholds, fixed in advance. Median assigned reads are 8.3 million, with a minimum of 0.64 million and a maximum of 15.7 million. **Nine samples that pass the deposited flag fall below 3 million assigned reads**, six of them bipolar I — and the 36 samples the deposit excluded have a *higher* floor, at 3.07 million, which confirms that depth played no part in the deposited flag. Four QC-passing samples have RIN below 5, the minimum being 2.3. We therefore require at least **3 million assigned reads and a RIN of at least 5.0**. The two sets may overlap, so the exact retained sample size will be computed and reported rather than assumed here. Both thresholds are recorded in the project configuration file before any analysis is run."))

A(("H2", "3.6 Gene filtering"))

A(("P", "Retaining genes with more than 10 counts in at least 90% of the 444 samples leaves **12,353 genes**. Krebs et al. report 12,344. The roughly nine-gene gap is an annotation-level difference rather than a pipeline error, and we report our own number. Our earlier draft used 12,343 in two places and 12,353 in a third: **12,353 is correct**, and the inconsistency is resolved here. One consequence of running the filter inside cross-validation folds, as Section 4.2 requires, is that the retained gene count differs in every fold because the filter sees fewer samples. That is the intended behaviour of a leak-free pipeline rather than an instability in it."))

A(("H2", "3.7 Deposited cell fractions"))

A(("P", "All 22 LM22 CIBERSORT fractions are present in the metadata and sum to 1.000000 per sample. Four types — follicular helper T cells, regulatory T cells, M1 macrophages and activated mast cells — are **exactly zero in all 480 samples**. These are structural zeros produced by the signature matrix rather than sampling zeros, and they are dropped rather than zero-replaced, since replacing them would manufacture variation that does not exist. Nine types are non-zero in more than half of samples and form the working set. Sequencing depth explains very little of the zero-inflation (Spearman ρ = 0.126 with the number of non-zero types), which points to signature-matrix misfit rather than to insufficient reads."))

A(("P", "Compared against published clinical reference intervals, and renormalised to the four comparable classes, control subjects give neutrophils at 38.8% (reference 40–70%, slightly under), lymphocytes at 36.6% (reference 20–40%, in range), monocytes at 24.6% (reference 2–8%, **roughly three times the upper bound**) and eosinophils at 0.0%. LM22 was constructed largely from purified, microarray-profiled immune populations and fits whole blood imperfectly; the monocyte inflation in particular is a property of the reference rather than an error in our handling. We report this as a preliminary result of the reliability comparison, and it is a substantial part of the motivation for running three deconvolution methods rather than trusting one."))

A(("P", "On practical arrangements: classic CIBERSORT fractions are already deposited and require no re-run. BayesPrism (Chu et al., 2022) runs locally at no cost. **CIBERSORTx (Newman et al., 2019) runs through its web portal and requires a registered, approved academic account rather than a local installation.** Our earlier text implied all three could be run locally while the flowchart showed the portal; the flowchart was correct and the text is corrected to match. Because portal approval has a lead time we do not control, the account request is the first item on the timeline in Section 6.4 rather than a step deferred until the deconvolution stage is reached."))

# ------------------------------------------------------------------ 4
A(("H1", "4. Analysis Plan"))

A(("P", "Figures 1–4 give the pipeline in diagram form and are referenced individually below. Where the text and a figure disagree, the text is authoritative: three of the diagrams contain errors identified in review, each noted in its caption, and all four will be redrawn for the full proposal."))

A(("H2", "4.1 Preprocessing: two parallel branches (Figure 1)"))

A(("P", "Preprocessing splits into two branches that are siblings rather than sequential stages, and the split exists because the two downstream uses require incompatible normalisations. The **cell branch** keeps all 57,773 genes and scales within each sample — TPM for CIBERSORT and CIBERSORTx, raw counts for BayesPrism, as each method requires. It keeps all genes because LM22 identifies cell types using 547 marker genes, and a gene filter tuned for differential expression deletes precisely the low-abundance markers that identify rare cell types. The **gene branch** filters to the 12,353 expressed genes, then applies TMM scaling (Robinson & Oshlack, 2010) followed by voom precision weights (Law et al., 2014) to produce log-CPM. Filtering precedes normalisation because near-zero genes distort TMM scaling factors, so reversing the order changes every value downstream. The two branches meet once, at residualisation, which requires both."))

A(("H2", "4.2 Leakage control"))

A(("P", "Data leakage is the principal technical risk in the prediction arm, and the rule we enforce is that any operation using information from more than one sample must be fitted inside the training fold. Operations that are genuinely per-sample may be computed once for the whole cohort: TPM scaling, classic CIBERSORT with quantile normalisation disabled, and the ILR formula itself each act on one sample at a time and cannot transmit information between folds. Everything else goes inside: the gene filter, TMM factors, voom weights, zero replacement, cell-type selection, gene ranking, feature scaling, residualisation coefficients and imputation models. Fit on train, transform test, never the reverse, and never fit so much as a column mean on held-out rows."))

A(("P", "This rule also determines which deconvolution method the prediction arm may use. Classic CIBERSORT with the fixed LM22 reference is admissible because it is per-sample. **CIBERSORTx batch correction is estimated across the cohort and is therefore transductive**, so it cannot appear inside a cross-validation fold; it belongs to the mediation and network arms and to the reliability comparison, where no train/test split exists. For the same reason, any decision about which deconvolution method performs best is itself a cross-sample decision and must be made inside training folds rather than once on all samples."))

A(("H2", "4.3 Arm 1 — the prediction contest (Figure 3)"))

A(("P", "This arm asks whether five compositional coordinates carry as much information about lithium use as the full transcriptome. Analysis is restricted to the 226 bipolar I subjects, since lithium varies only within that group. Three feature sets compete: the filtered gene matrix, the five ILR coordinates, and the gene matrix residualised on the ILR coordinates, for the reason given in Section 2.1."))

A(("P", "**The single train/test split of our earlier draft is abandoned.** A 10% test set drawn from 226 subjects contains roughly 23 samples and about 7 non-users, which cannot establish equivalence between two classifiers at any useful precision. It is replaced by **repeated nested cross-validation**: an outer 5-fold loop for evaluation, an inner 5-fold loop within each outer training fold for hyperparameter tuning, and the whole procedure repeated 10 times with different partitions. Tuning inside the folds used for evaluation — which is what Figure 3 currently depicts — biases the performance estimate optimistically, because hyperparameters are then chosen with sight of the data they are scored on. The inner loop exists specifically to prevent this and will be added to the diagram."))

A(("P", "Two learners are applied to all three feature sets. **Elastic net** (Zou & Hastie, 2005) is the appropriate linear model for the gene arm, where the number of predictors (about 12,353) greatly exceeds the number of subjects (226) and predictors are heavily correlated: the L1 penalty produces a sparse solution, while the L2 penalty prevents correlated co-expressed genes from being dropped arbitrarily, which matters when several genes carry the same underlying signal. **Random forest** (Breiman, 2001) is included because the ILR arm has only five predictors, a regime in which a nonparametric learner can capture interactions and threshold effects between lineage balances that a linear model cannot represent. Running both learners on all three feature sets is not redundancy but a fairness requirement: with only one learner, an apparent difference between feature sets could simply reflect a model class that happens to suit one representation. We report the best-tuned model per feature set from the full two-by-three grid (Greener et al., 2022)."))

A(("P", "Performance is measured by AUC. Significance against chance uses a **permutation null of 1,000 label permutations**, with the entire in-fold pipeline re-run under each permutation so that the null absorbs any optimism the procedure itself introduces. The comparison between feature sets uses DeLong’s test for correlated ROC curves (DeLong et al., 1988) for the difference, and **two one-sided tests** (Schuirmann, 1987) against the pre-declared margin of ΔAUC = 0.05 for equivalence, with percentile bootstrap confidence intervals across the repeated-CV replicates. Equivalence and difference are separate claims: failing to find a difference is not evidence of equivalence, and conflating the two is the error the original single-split analysis makes."))

A(("H2", "4.4 Compositional coordinates and zero replacement"))

A(("P", "Cell fractions are compositional: they sum to one, so they occupy a simplex rather than Euclidean space, and they cannot all enter a regression because any one is determined by the others (Aitchison, 1982). Raw proportions also produce spurious negative correlations, since an increase in one type forces the others down even when no absolute decrease has occurred. We therefore use **isometric log-ratio coordinates** (Egozcue et al., 2003), which map the simplex into Euclidean space without redundancy."))

A(("P", "The ILR basis is not unique, and the choice of basis determines whether the results are interpretable. We build ours on a **hematopoietic lineage tree** — what Figure 2 calls a lineage balance tree, a term our earlier text never defined. Each internal node of the tree contributes one coordinate, called a balance, which is the normalised log ratio of the geometric mean abundance of the cell types on one branch to that of the types on the other. Splitting first at myeloid versus lymphoid, then within each lineage, yields coordinates that read as biological quantities: the first balance is the myeloid-to-lymphoid ratio, which is precisely the quantity lithium is expected to move. From the retained cell types this produces five balances. We will publish the tree and the composition of every balance alongside the results, because a per-coordinate effect is uninterpretable without knowing which cell types it contrasts."))

A(("P", "Log ratios are undefined at zero, and CIBERSORT returns exact zeros, so the two kinds of zero must be distinguished. The four types that are zero in all 480 samples are **structural** — the signature matrix cannot detect them in this tissue — and are dropped entirely, since replacing them would invent variation. Remaining zeros are treated as below-detection values and handled by **multiplicative simple replacement at 65% of the per-type detection limit** (Martín-Fernández et al., 2003), which preserves the ratios among the non-zero parts, unlike additive replacement. Because this choice is arbitrary within a range, and the question of whether it changes the ratios is a fair one, we pre-specify a **sensitivity analysis over the replacement rule**: the multiplicative rule at 50%, 65% and 80% of the detection limit, plus a Bayesian-multiplicative alternative. All downstream results are recomputed under each. If the conclusions move, the replacement rule is reported as a limitation rather than quietly fixed at whichever value proves most convenient."))

A(("H2", "4.5 Arm 2 — mediation (Figure 2)"))

A(("P", "The mediation arm quantifies how much of lithium’s effect on gene expression runs through cell composition and how much does not (Kartiosuo et al., 2024; VanderWeele & Vansteelandt, 2014). Our earlier statement that we would “run different mediation analyses, switching up the exposure, mediator and outcome” describes a search over models rather than a test, and would inflate false positives with no correction accounting for the search. **We therefore pre-specify a single primary model here** and designate every other configuration exploratory, to be reported as such and never as a confirmatory result."))

A(("P", "The primary model takes lithium use as exposure, the five ILR coordinates as mediator, and per-gene log-CPM as outcome, adjusted for age, sex, tobacco use, RIN, sequencing plate and the three sequencing-metric PCs, on the 226 bipolar I subjects, with assessment group dropped as constant. Estimation follows the product of coefficients (Baron & Kenny, 1986), a method Figure 2 names but our earlier text never explained. The exposure-to-mediator path *a* is estimated by regressing each ILR coordinate on lithium and covariates; the mediator-to-outcome path *b* is estimated by regressing each gene on the ILR coordinates, lithium and covariates; the indirect effect is the product *ab* summed over coordinates; the direct effect is the remaining lithium coefficient *c*′; and the proportion mediated is *ab* / (*ab* + *c*′). All 12,353 outcome models are fitted as a single matrix operation rather than in a loop. Uncertainty comes from a **bias-corrected and accelerated bootstrap over subjects with 5,000 resamples**, since the product of two normal estimates is not itself normal, and multiplicity is controlled by Benjamini–Hochberg (Benjamini & Hochberg, 1995) at FDR 0.05 across genes."))

A(("P", "**The product of coefficients assumes no exposure-by-mediator interaction, and that assumption must be tested rather than asserted.** If lithium’s effect on expression depends on the cell mixture — plausible if lithium acts differently in a neutrophil-dominated sample than in a lymphocyte-dominated one — then the product of coefficients is not a valid decomposition and the proportion it reports is not interpretable. We therefore fit the outcome model with a lithium × ILR interaction term **before** reporting any proportion mediated. The decision rule is fixed now: if no interaction term survives Benjamini–Hochberg at FDR 0.05, we report the product of coefficients; if interaction is present, we switch to the counterfactual formulation of Valeri and VanderWeele (2013) and report natural direct and natural indirect effects, which remain well defined under exposure–mediator interaction. Fixing the rule in advance prevents the choice from being made after seeing which estimator gives the more favourable answer."))

A(("P", "Mediation further assumes no unmeasured confounding of the exposure–mediator, mediator–outcome and exposure–outcome relationships. That assumption is certainly violated here: illness severity, body composition and other psychotropic medications each plausibly affect lithium prescription, blood composition and expression simultaneously, and none of them is recorded. Rather than assume them away we bound them with **E-values** (VanderWeele & Ding, 2017), which report the minimum strength of association an unmeasured confounder would need with both exposure and outcome in order to explain away the estimate. The bounds are chosen from published literature and declared in advance rather than tuned to the result: body fat is anchored on the neutrophil-to-lymphocyte associations reported by Furuncuoğlu et al. (2016), and severity and co-medication are anchored on the largest effects reported in the psychiatric transcriptomic literature we cite. An E-value below the plausible confounder strength from that literature will be reported as a failure to exclude confounding, not as a caveat attached to a positive claim."))

A(("H2", "4.6 Circularity: the mediator is estimated from the outcome"))

A(("P", "The most serious methodological threat to Arm 2 is that the cell fractions are estimated from the same expression matrix that serves as the outcome. For the 547 LM22 marker genes the relationship is close to tautological: the fraction is a fitted function of those genes’ expression, so regressing them on the fraction partly recovers the deconvolution algebra rather than any biology. Four procedures address this, of which the first three are requirements rather than optional extras."))

A(("PL", "**Marker exclusion.** All 547 LM22 marker genes are excluded from the primary Arm 2 outcome set, and the headline proportion mediated is computed on non-marker genes only."))

A(("PL", "**Stratified reporting.** The proportion mediated is reported separately for marker and non-marker genes. If circularity is inflating the estimate, markers will show a markedly higher proportion, and the size of that gap is a direct empirical readout of the bias rather than a guess at it."))

A(("PL", "**Cross-method sensitivity.** The proportion mediated is re-estimated using fractions from CIBERSORTx and from BayesPrism. The three methods share an input matrix but differ in signature matrix, algorithm and noise model, so the spread of the estimate across methods bounds the component attributable to any one algorithm’s idiosyncrasies. This promotes the deconvolution comparison from a standalone side study to a required sensitivity analysis for the mediation result."))

A(("PL", "**Honest statement of the residual.** None of the above removes circularity completely: any mediator derived from expression remains a function of the outcome matrix, and we will say so rather than claim the problem is solved. Usefully, the two principal biases act in opposite directions — circularity inflates the mediated proportion, while measurement error in an estimated mediator attenuates it. We therefore report the uncorrected product-of-coefficients estimate as a **lower bound**, apply **regression calibration** (Carroll et al., 2006) using the between-method variance as the measurement-error estimate to correct the attenuation, and use the marker/non-marker gap to bound the inflation. Both corrections are reported separately, so that a reader can see the direction and magnitude of each rather than a single opaque number."))

A(("H2", "4.7 Arm 3 — co-expression networks (Figure 4)"))

A(("P", "Weighted gene co-expression networks are built from gene–gene correlations (Langfelder & Horvath, 2008) for three groups: controls, bipolar I off lithium and bipolar I on lithium. Module preservation is scored with the Zsummary and medianRank statistics of Langfelder et al. (2011), and the whole analysis is then repeated on expression residualised on the ILR coordinates, to ask whether any difference survives the removal of composition."))

A(("P", "Group comparison requires care about which pair isolates which effect, a point our earlier draft did not address. Controls differ from patients in far more than lithium, so a control-versus-lithium-user contrast confounds illness with medication and isolates neither. **The pair that isolates lithium is bipolar I on lithium against bipolar I off lithium**, since both groups carry the diagnosis. The pair that isolates illness, as far as this dataset permits, is controls against bipolar I off lithium, subject to the caveat in Section 3.4 that those patients may take other psychotropics and to the filtered-control-group caveat of Section 3.1. We designate the on-versus-off-lithium comparison primary for this arm and report the others as secondary, each labelled with what it confounds."))

A(("P", "Group sizes are unequal — 74 off lithium against 152 on lithium and 205 controls — and network statistics are strongly sample-size dependent, so groups are subsampled to 74 for comparability. Subsampling to 74 discards most of the control group, which raises a question our earlier draft did not ask: whether modules detected in 74 subjects are stable at all. **We therefore check module stability before comparing groups.** Modules are built independently in each of 500 draws, and cross-draw stability is quantified by the adjusted Rand index of module assignments and by the proportion of draws in which each module recurs. Only modules recurring in at least 80% of draws proceed to the group comparison; unstable modules are reported as unstable rather than compared. Our earlier flowchart read “500-100 draws”, which was a typo; the figure is 500."))

A(("P", "Preservation statistics are pooled across draws before multiplicity correction rather than after, since applying Benjamini–Hochberg to each draw separately would treat 500 correlated resamples of the same data as 500 independent tests. For each module we take the median Zsummary across draws as the point estimate, and the 2.5th and 97.5th percentiles across draws as the interval, then apply Benjamini–Hochberg once across modules. A module counts as differing between groups when its pooled Zsummary is below 2 and its corrected p-value is below 0.05."))

A(("H2", "4.8 Side analyses"))

A(("P", "**Deconvolution reliability.** Because the dataset contains no measured blood counts, there is no ground truth against which to rank the three methods, and selecting a “best” method by accuracy is therefore not possible. Our earlier text proposed comparing fractions “against a reference of what cell fractions are supposed to be” without saying what that reference was. We now make it explicit and reframe the comparison from accuracy to **reliability and plausibility**, judged on three criteria fixed in advance. First, **agreement**: intraclass correlation per cell type across methods, together with Aitchison distance between whole compositions. Second, **plausibility**: comparison against published clinical reference intervals for whole blood, as reported in Section 3.7. Third, **recovery of a known result**, described next. Where the three methods agree, downstream conclusions are robust to the choice; where they disagree, the disagreement propagates into the mediation estimate as an explicit uncertainty band rather than being concealed by picking a winner."))

A(("P", "**Positive control.** Krebs et al. (2020) reported elevated neutrophil proportions in the lithium users of this dataset. That is a published result with a known answer in the exact data we are analysing, and it therefore serves as a validity gate: **before any arm is reported, our deconvolution must reproduce the direction and approximate magnitude of that neutrophil elevation.** If it does not, the fractions are not fit for purpose and no downstream result is reportable, however favourable the reliability statistics may look. This check runs first, on the deposited CIBERSORT fractions, and is then repeated for each method."))

A(("P", "**Illness retest.** Differential expression is re-run for controls against the 74 bipolar I subjects not taking lithium, without a lithium covariate, for the over-adjustment reason given in Section 1. Significance is assessed against a permutation null rather than against nominal p-values, and the results are reported alongside two caveats: that the control group is the filtered one of Section 3.1, and that the cases may be taking unrecorded psychotropics."))

A(("H2", "4.9 Pre-specified parameters"))

A(("P", "Every threshold below is fixed in a configuration file before any result is examined, and the file is version-controlled so that the commit history establishes that the values preceded the results. A margin chosen after the fact is not a test, and the configuration file is how we make that claim checkable rather than merely assert it."))

A(("TBLROW", "Parameter|Pre-specified value"))
A(("TBLROW", "Equivalence margin (H1)|ΔAUC = 0.05, two one-sided tests at α = 0.05"))
A(("TBLROW", "Cross-validation|Outer 5-fold, inner 5-fold for tuning, 10 repeats"))
A(("TBLROW", "Permutation null|1,000 label permutations, full in-fold pipeline re-run per permutation"))
A(("TBLROW", "Minimum library size|3,000,000 assigned reads"))
A(("TBLROW", "Minimum RIN|5.0"))
A(("TBLROW", "Gene filter|More than 10 counts in at least 90% of training-fold samples"))
A(("TBLROW", "Cell types retained|LM22 types non-zero in more than 50% of samples; 4 structural zeros dropped"))
A(("TBLROW", "Zero replacement|Multiplicative simple replacement at 65% of detection limit; sensitivity at 50%, 80% and Bayesian-multiplicative"))
A(("TBLROW", "ILR basis|Hematopoietic lineage tree, first split myeloid vs lymphoid; 5 balances, published with results"))
A(("TBLROW", "Primary mediation model|Exposure lithium; mediator 5 ILR balances; outcome log-CPM of non-marker genes; covariates age, sex, tobacco, RIN, plate, seq-PC1–3"))
A(("TBLROW", "Interaction test|Lithium × ILR, BH at FDR 0.05, tested before any proportion mediated is reported"))
A(("TBLROW", "Mediation inference|Product of coefficients; BCa bootstrap over subjects, 5,000 resamples; BH at FDR 0.05"))
A(("TBLROW", "Proportion mediated threshold (H2)|Greater than 0.5 after measurement-error correction"))
A(("TBLROW", "Module preservation threshold (H3)|Zsummary below 2, pooled across draws, BH at FDR 0.05"))
A(("TBLROW", "Module stability gate|Module must recur in at least 80% of draws to be compared"))
A(("TBLROW", "Network subsampling|74 per group, 500 draws"))
A(("TBLROW", "Random seed|Single seed set in configuration, threaded through every stochastic step"))

# ------------------------------------------------------------------ 5
A(("H1", "5. Expected Results and Interpretation"))

A(("P", "For H1, support means the five ILR coordinates achieving a cross-validated AUC whose difference from the gene matrix has a 95% confidence interval contained entirely within ±0.05, with both feature sets significantly above the permutation null. If the gene matrix exceeds the coordinates by more than the margin, H1 is rejected and the transcriptome carries information about lithium exposure that a cell count does not. A third outcome is possible and would be uninformative rather than negative: if the interval is wide enough to contain both zero and the margin, we are underpowered for an equivalence claim, and we will report that rather than presenting a non-significant difference as though it established equivalence. The residualised-expression comparator then interprets whichever result obtains, as set out in Section 2.1."))

A(("P", "For H2, support means an aggregate proportion mediated above 0.5 with a bootstrap interval excluding 0.5, concentrated in the myeloid-to-lymphoid balance, and with a marker/non-marker gap small enough that circularity does not account for the estimate. Our earlier draft said supporting results would be lithium raising the myeloid-to-lymphoid ratio **only**, which was too strong: it would make any additional lineage shift falsify the hypothesis, and that was not the intention. Lithium acting on several lineages is entirely compatible with composition mediating most of its expression effect. We therefore state the expectation as **primarily** myeloid-to-lymphoid, with the balance-wise decomposition reported in full so that readers can see whether the effect is concentrated or distributed. What would genuinely contradict H2 is a proportion mediated at or below 0.5, or a direct effect that remains large once composition is accounted for — and given that Boltz et al. detected lithium-associated genes after composition adjustment, a partially direct effect is the outcome we should honestly regard as likely."))

A(("P", "For H3, support means at least one module with a pooled Zsummary below 2 surviving correction, among modules that pass the stability gate. The more informative comparison is what happens after residualisation: a difference that vanishes once composition is removed indicates a compositional rather than a regulatory effect, consistent with H2, whereas a difference that persists indicates altered co-regulation, which composition adjustment in the previous literature could not have detected. Complete module preservation across all three groups would be a clean negative result and would be reported as such, with the effect sizes and intervals that make a null informative."))

# ------------------------------------------------------------------ 6
A(("H1", "6. Feasibility, Risks and Mitigation"))

A(("H2", "6.1 The three arms are not independent"))

A(("P", "Our earlier draft claimed the three arms run independently, so that a failure in one would leave the others intact. That is **not correct**, and the correction matters because it identifies the project’s single point of failure. All three arms consume the same cell fractions: Arm 1 uses them as features, Arm 2 as the mediator, Arm 3 as the residualisation basis. If deconvolution fails, all three fail together."))

A(("P", "Partial failure is moreover not hypothetical. It is already visible in Section 3.7, where monocytes sit at roughly three times their reference upper bound and four of 22 cell types are structurally undetectable. LM22 was not built for whole blood, and at 22-type resolution it plainly misfits this tissue. Our backup is therefore specified in advance rather than improvised: **collapse to coarse lineage resolution.** A single myeloid-versus-lymphoid balance is far more robust to signature-matrix misfit than 22-type resolution, because errors that redistribute mass *within* a lineage cancel once the lineages are aggregated, and misallocation between neighbouring T-cell subtypes is exactly the failure mode LM22 exhibits. If the three methods disagree at fine resolution but agree at the lineage level, as measured by the intraclass correlations of Section 4.8, we run all three arms on the coarse composition and report the reduced resolution as a finding about LM22 rather than as a workaround. H1 would then test one balance instead of five, which is a weaker but still meaningful claim, since a single ratio is obtainable from a routine differential blood count. If the methods disagree even at lineage level, or if the positive control of Section 4.8 fails, we stop and report that whole-blood deconvolution with currently available references is not reliable enough to support the question. That is a negative methodological result, publishable as such, and considerably more useful than three arms built on fractions we do not trust."))

A(("H2", "6.2 Leakage, and why the pipeline is built to make it visible"))

A(("P", "Rebuilding the gene branch inside every fold means that filtering, normalisation, scaling and residualisation run hundreds of times, and each repetition is an opportunity for held-out data to leak into a fitted quantity. Three measures reduce that risk. Arms 2 and 3 and the side analyses consume cached objects built once on all 444 samples, while **Arm 1 is forbidden from touching that cache** and rebuilds the gene side within each fold; this makes the leak-prone path structurally separate from the rest of the code rather than interleaved with it. Cached objects are keyed by a hash of the code that produced them, so a stale matrix cannot silently be analysed after the code that made it has changed. And a test suite asserts every verified quantity in Section 3 — the sample counts, the 74/152 lithium split, the Fisher p-value, the 12,353 gene count, the structural zeros — so that a change breaking any of them fails loudly rather than propagating into a result."))

A(("H2", "6.3 Statistical power"))

A(("P", "For the mediation arm at 226 subjects, the two paths are powered very differently. The exposure-to-mediator path *a* compares 74 non-users against 152 users, and at 80% power and α = 0.05 two-sided it detects a standardised difference of **d ≈ 0.40** in an ILR coordinate. The neutrophil shift Krebs et al. report is comfortably larger than this, so path *a* is adequately powered and we expect to recover it. The mediator-to-outcome path *b* is the binding constraint: with 226 subjects and eleven covariates, 80% power at a per-gene threshold of α = 10⁻⁴ — a realistic Benjamini–Hochberg operating point across 12,353 tests — requires a partial correlation of **r ≈ 0.33**. Genes coupled to composition more weakly than that will not reach gene-level significance, so the per-gene mediation results should be read as a **floor on the number of mediated genes rather than a census of them**."))

A(("P", "This is precisely why the **aggregate proportion mediated is the primary estimand for H2**, rather than a count of significant genes. The aggregate pools information across all 12,353 outcome models and is far better powered than any individual gene-level test, and it is also the quantity the scientific question actually asks about. We report it with a BCa bootstrap interval over subjects, and report the gene-level count alongside it, explicitly labelled as a lower bound."))

A(("P", "H4 is a different matter. Detecting moderated mediation requires establishing a **difference between two mediated effects** estimated in subgroups of 74 and 152. Interaction tests generally require roughly four times the sample size of main-effect tests of comparable standardised magnitude, and at these group sizes we would be powered only for a moderation effect approaching the size of the mediated effect itself, which is not a plausible target. We therefore declare H4 exploratory in advance, will report it as an estimate with an interval and no significance claim, and will not allow it to contribute to the project’s conclusions. Declaring this now, rather than after seeing the result, is the point of saying it here."))

A(("H2", "6.4 Practical risks and sequence of work"))

A(("P", "The CIBERSORTx portal account requires academic registration and approval on a schedule we do not control, so the request is submitted immediately rather than when the deconvolution stage is reached. BayesPrism runs locally and classic CIBERSORT fractions are already deposited, so a delayed or refused account costs us one of three methods rather than the comparison itself. BayesPrism is computationally heavy and will be benchmarked on a small subset of samples before a full run is committed to. Disagreement among the three methods is not treated as a failure mode: as described in Section 4.6, the spread becomes an explicit uncertainty band on the mediation estimate, which is more informative than a single number drawn from an arbitrarily chosen method."))

A(("P", "The binding sample-size constraint throughout is the 74 bipolar I subjects off lithium, which caps the network arm and the illness retest as well as path *a* of the mediation. Where an analysis proves underpowered we will report the effect size with its confidence interval rather than a bare non-significant p-value, so that a null result bounds the effect rather than merely failing to detect it. Work proceeds in the order set out above — loading and quality control; the test suite asserting Section 3; preprocessing; deconvolution and the positive control; then mediation, prediction, and finally the side tests and networks — with each stage required to pass before the next begins, so that a problem is caught at the stage that caused it rather than in the results."))

# ------------------------------------------------------------------ figures
A(("H1", "Figures"))

A(("FIG", "0"))
A(("CAP", "**Figure 1. Preprocessing module.** The cell branch retains all 57,773 genes and scales within samples; the gene branch filters to 12,353 genes and then applies TMM and voom. *Corrections applied in the text:* the imputation step is withdrawn, since all covariates are complete post-QC (Section 3.2); the “use the best method” step is replaced by the reliability-and-plausibility framework of Section 4.8, because this dataset contains no measured blood counts to serve as ground truth; and our own depth and RIN screen (Section 3.5) is applied, which the deposited quality flag does not perform."))

A(("FIG", "1"))
A(("CAP", "**Figure 2. Mediation arm.** Paths *a*, *b* and *c* are estimated by least squares and combined by the product of coefficients, with bootstrap intervals, Benjamini–Hochberg correction and regression calibration for the estimated mediator. *Corrections applied in the text:* a lithium × ILR interaction test is added before any proportion mediated is reported (Section 4.5), since the product of coefficients is invalid under interaction; the note about running the analysis “a couple of different ways” is replaced by a single pre-specified primary model; and the circularity procedures of Section 4.6 are added. “Lineage balance tree” and “product of coefficients” are defined in Sections 4.4 and 4.5 respectively."))

A(("FIG", "2"))
A(("CAP", "**Figure 3. Prediction contest arm.** *Corrections applied in the text:* the single 10% test split is replaced by repeated nested cross-validation (Section 4.3), since roughly seven held-out non-users cannot support an equivalence claim; an **inner tuning loop** is required, because tuning within the evaluation folds shown here biases the estimate optimistically; a third feature set, expression residualised on the ILR coordinates, is added to separate prediction from mediation (Section 2.1); and the choice of elastic net and random forest is justified in Section 4.3."))

A(("FIG", "3"))
A(("CAP", "**Figure 4. Network analysis arm.** *Corrections applied in the text:* “500-100 draws” was a typo and the figure is 500 draws; a module stability gate is added before group comparison, since subsampling to 74 discards most controls (Section 4.7); preservation statistics are pooled across draws before Benjamini–Hochberg rather than after, because 500 resamples of the same data are not 500 independent tests; and the primary group contrast is specified as bipolar I on lithium versus bipolar I off lithium, the only pair that isolates medication from diagnosis."))

# ------------------------------------------------------------------ references
A(("H1", "References"))

REFS = [
 "Aitchison, J. (1982). The statistical analysis of compositional data. *Journal of the Royal Statistical Society: Series B*, 44(2), 139–177. https://doi.org/10.1111/j.2517-6161.1982.tb01195.x",
 "Barnett, J. H., & Smoller, J. W. (2009). The genetics of bipolar disorder. *Neuroscience*, 164(1), 331–343. https://doi.org/10.1016/j.neuroscience.2009.03.080",
 "Baron, R. M., & Kenny, D. A. (1986). The moderator–mediator variable distinction in social psychological research: conceptual, strategic, and statistical considerations. *Journal of Personality and Social Psychology*, 51(6), 1173–1182. https://doi.org/10.1037/0022-3514.51.6.1173",
 "Barr, R. D., & Galbraith, P. R. (1983). Lithium and hematopoiesis. *Canadian Medical Association Journal*, 128(2), 123–126.",
 "Benjamini, Y., & Hochberg, Y. (1995). Controlling the false discovery rate: a practical and powerful approach to multiple testing. *Journal of the Royal Statistical Society: Series B*, 57(1), 289–300. https://doi.org/10.1111/j.2517-6161.1995.tb02031.x",
 "Boltz, T., Schwarz, T., Bot, M., Hou, K., Caggiano, C., Lapinska, S., Duan, C., Boks, M. P., Kahn, R. S., Zaitlen, N., Pasaniuc, B., & Ophoff, R. (2024). Cell-type deconvolution of bulk-blood RNA-seq reveals biological insights into neuropsychiatric disorders. *American Journal of Human Genetics*, 111(2), 323–337. https://doi.org/10.1016/j.ajhg.2023.12.018",
 "Breiman, L. (2001). Random forests. *Machine Learning*, 45(1), 5–32. https://doi.org/10.1023/A:1010933404324",
 "Carroll, R. J., Ruppert, D., Stefanski, L. A., & Crainiceanu, C. M. (2006). *Measurement Error in Nonlinear Models: A Modern Perspective* (2nd ed.). Chapman & Hall/CRC. https://doi.org/10.1201/9781420010138",
 "Chu, T., Wang, Z., Pe’er, D., & Danko, C. G. (2022). Cell type and gene expression deconvolution with BayesPrism enables Bayesian integrative analysis across bulk and single-cell RNA sequencing in oncology. *Nature Cancer*, 3(4), 505–517. https://doi.org/10.1038/s43018-022-00356-3",
 "DeLong, E. R., DeLong, D. M., & Clarke-Pearson, D. L. (1988). Comparing the areas under two or more correlated receiver operating characteristic curves: a nonparametric approach. *Biometrics*, 44(3), 837–845. https://doi.org/10.2307/2531595",
 "Egozcue, J. J., Pawlowsky-Glahn, V., Mateu-Figueras, G., & Barceló-Vidal, C. (2003). Isometric logratio transformations for compositional data analysis. *Mathematical Geology*, 35(3), 279–300. https://doi.org/10.1023/A:1023818214614",
 "Furuncuoğlu, Y., Tulgar, S., Dogan, A. N., Cakar, S., Tulgar, Y. K., & Cakiroglu, B. (2016). How obesity affects the neutrophil/lymphocyte and platelet/lymphocyte ratio, systemic immune-inflammatory index and platelet indices: a retrospective study. *European Review for Medical and Pharmacological Sciences*, 20(7), 1300–1306.",
 "Greener, J. G., Kandathil, S. M., Moffat, L., et al. (2022). A guide to machine learning for biologists. *Nature Reviews Molecular Cell Biology*, 23(1), 40–55. https://doi.org/10.1038/s41580-021-00407-0",
 "Kartiosuo, N., Nevalainen, J., Raitakari, O., Pahkala, K., & Auranen, K. (2024). Hypothesis-driven mediation analysis for compositional data: an application to gut microbiome. *Biostatistics & Epidemiology*, 8(1). https://doi.org/10.1080/24709360.2024.2360375",
 "Kast, R. E. (2008). How lithium treatment generates neutrophilia by enhancing phosphorylation of GSK-3, increasing HIF-1 levels and how this path is important during engraftment. *Bone Marrow Transplantation*, 41(1), 23–26. https://doi.org/10.1038/sj.bmt.1705872",
 "Krebs, C. E., Ori, A. P. S., Vreeker, A., Wu, T., Cantor, R. M., Boks, M. P. M., Kahn, R. S., Olde Loohuis, L. M., & Ophoff, R. A. (2020). Whole blood transcriptome analysis in bipolar disorder reveals strong lithium effect. *Psychological Medicine*, 50(15), 2575–2586. https://doi.org/10.1017/S0033291719002745",
 "Langfelder, P., & Horvath, S. (2008). WGCNA: an R package for weighted correlation network analysis. *BMC Bioinformatics*, 9, 559. https://doi.org/10.1186/1471-2105-9-559",
 "Langfelder, P., Luo, R., Oldham, M. C., & Horvath, S. (2011). Is my network module preserved and reproducible? *PLoS Computational Biology*, 7(1), e1001057. https://doi.org/10.1371/journal.pcbi.1001057",
 "Law, C. W., Chen, Y., Shi, W., & Smyth, G. K. (2014). voom: precision weights unlock linear model analysis tools for RNA-seq read counts. *Genome Biology*, 15(2), R29. https://doi.org/10.1186/gb-2014-15-2-r29",
 "Martín-Fernández, J. A., Barceló-Vidal, C., & Pawlowsky-Glahn, V. (2003). Dealing with zeros and missing values in compositional data sets using nonparametric imputation. *Mathematical Geology*, 35(3), 253–278. https://doi.org/10.1023/A:1023866030544",
 "Newman, A. M., Liu, C. L., Green, M. R., Gentles, A. J., Feng, W., Xu, Y., Hoang, C. D., Diehn, M., & Alizadeh, A. A. (2015). Robust enumeration of cell subsets from tissue expression profiles. *Nature Methods*, 12(5), 453–457. https://doi.org/10.1038/nmeth.3337",
 "Newman, A. M., Steen, C. B., Liu, C. L., et al. (2019). Determining cell type abundance and expression from bulk tissues with digital cytometry. *Nature Biotechnology*, 37(7), 773–782. https://doi.org/10.1038/s41587-019-0114-2",
 "Robinson, M. D., & Oshlack, A. (2010). A scaling normalization method for differential expression analysis of RNA-seq data. *Genome Biology*, 11(3), R25. https://doi.org/10.1186/gb-2010-11-3-r25",
 "Rubin, D. B. (1987). *Multiple Imputation for Nonresponse in Surveys*. John Wiley & Sons. https://doi.org/10.1002/9780470316696",
 "Salarda, E. M., Zhao, N. O., Lima, C. N. N. C., & Fries, G. R. (2021). Mini-review: The anti-aging effects of lithium in bipolar disorder. *Neuroscience Letters*, 759, 136051. https://doi.org/10.1016/j.neulet.2021.136051",
 "Schuirmann, D. J. (1987). A comparison of the two one-sided tests procedure and the power approach for assessing the equivalence of average bioavailability. *Journal of Pharmacokinetics and Biopharmaceutics*, 15(6), 657–680. https://doi.org/10.1007/BF01068419",
 "Valeri, L., & VanderWeele, T. J. (2013). Mediation analysis allowing for exposure–mediator interactions and causal interpretation: theoretical assumptions and implementation with SAS and SPSS macros. *Psychological Methods*, 18(2), 137–150. https://doi.org/10.1037/a0031034",
 "VanderWeele, T. J., & Ding, P. (2017). Sensitivity analysis in observational research: introducing the E-value. *Annals of Internal Medicine*, 167(4), 268–274. https://doi.org/10.7326/M16-2607",
 "VanderWeele, T. J., & Vansteelandt, S. (2014). Mediation analysis with multiple mediators. *Epidemiologic Methods*, 2(1), 95–115. https://doi.org/10.1515/em-2012-0010",
 "Wang, L., Oh, W., & Zhu, J. (2016). Disease-specific classification using deconvoluted whole blood gene expression. *Scientific Reports*, 6(1), 32976. https://doi.org/10.1038/srep32976",
 "Zou, H., & Hastie, T. (2005). Regularization and variable selection via the elastic net. *Journal of the Royal Statistical Society: Series B*, 67(2), 301–320. https://doi.org/10.1111/j.1467-9868.2005.00503.x",
]
for _r in REFS:
    A(("REF", _r))
